rpc:
  server:
    port: 9991
    registry-addr: 192.168.150.160:2181
    provider-name: server-01
    registry: zookeeper
    transport: netty
    rate-limiter:
      strategy: no_limiter
#      strategy: token_bucket
#      capacity: 100
#      refill-tokens: 100
#      refill-interval: 1000

